trigger:
  - none
pr:
  - none
parameters:
  - name: enviroment
    displayName: enviorment to deploy
    type: string
    default: sandbox
    values: 
      - dev
      - sandbox
      - test
      - prod
      
stages:
  - stage: createInfra
    displayName: createInfra
    jobs:
      - job: jobTest
        displayName: jobTest
        steps:
          - bash: |
              echo "This is testBranch"
              - task: TerraformTaskV3@3
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'UKDDC_Azure_Subscription'
                  backendAzureRmResourceGroupName: 'taggarta-sandbox-rg'
                  
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo 'Hello world'

  - stage: destroyInfra
    displayName: destroyInfra
